name: .NET

on: push

env:
  Config: Release

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup env
        id: setupenv
      # TODO Version depending on prerelease, use alpha otherwise
        run: |
          vdate=$(date -u "+%Y%m%d%H%M")
          version=0.0.5-alpha$vdate
          echo "version=$version" >> "$GITHUB_ENV"
      - uses: actions/checkout@v3

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"
      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: echo "$STEPS_CONTEXT"
      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}
        run: echo "$RUNNER_CONTEXT"
      - name: Dump strategy context
        env:
          STRATEGY_CONTEXT: ${{ toJson(strategy) }}
        run: echo "$STRATEGY_CONTEXT"
      - name: Dump matrix context
        env:
          MATRIX_CONTEXT: ${{ toJson(matrix) }}
        run: echo "$MATRIX_CONTEXT"

      - name: Show default environment variables
        run: |
          echo "The job_id is: $GITHUB_JOB"   # reference the default environment variables
          echo "The id of this action is: $GITHUB_ACTION"   # reference the default environment variables
          echo "The run id is: $GITHUB_RUN_ID"
          echo "The GitHub Actor's username is: $GITHUB_ACTOR"
          echo "GitHub SHA: $GITHUB_SHA"

      - name: Write to Job Summary
        if: success() || failure()
        run: echo "#WiHiiii" >> "$GITHUB_STEP_SUMMARY"

      - name: Release test ${{ vars.GITHUB_REPOSITORY_OWNER }}
        run: |
          echo $GITHUB_REPOSITORY_OWNER
          ls -lha
