name: .NET

on:
  push:
  release:
  
env:
  Config: Release

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      actionpath: ${{ github.repository }}/actions/runs/${{ github.run_id }}
    steps:
      - name: Setup env ${{ vars.GITHUB_REPOSITORY_OWNER }} event ${{ github.event_name }} action  ${{ github.event.action }} ref ${{ github.ref }}
        id: setupenv
        run: |
          echo "Tag name from github.ref_name: ${{ github.ref_name }} env $GITHUB_REF_NAME"
          echo "Ref name from github.ref: ${{ github.ref }} env $GITHUB_REF"
          echo "The job_id is: ${{ github.job }} $GITHUB_JOB"
          echo "The id of this action is: $GITHUB_ACTION"
          echo "The run id is: ${{ github.run_id }}"
          echo "The GitHub Actor's username is: ${{ github.actor }}"
          echo "GitHub SHA: ${{ github.sha }} env: $GITHUB_SHA"
          version=$(date -u "+%Y.%m.%d-alpha%H%M")
          SHORT_SHA=$(echo ${{ github.sha }} | cut -c1-8)
          if [[ ${{ github.ref }} =~ ^refs/tags/v([0-9][0-9][0-9][0-9]\.[0-9]+\.[0-9]+)$ ]]; then
              # override alpha version
              if [[ ${{ github.event_name }} == release ]]; then
                  version=${BASH_REMATCH[1]}
              else
                  version=${BASH_REMATCH[1]}-beta$SHORT_SHA
              fi
          fi
          echo got version $version
          echo "early summary version ${{ env.version }} $version" >> "$GITHUB_STEP_SUMMARY"
          echo "version=$version" >> "$GITHUB_ENV"
          curl -s https://api.github.com/repos/${{ env.actionpath }}/jobs
      - name: Set release version
        if: startsWith(github.ref, 'refs/tags/v') && github.event.release.published
        run: |
          relversion=$GITHUB_REF_NAME
          echo "relversion=$relversion" >> "$GITHUB_ENV"
          
      - uses: actions/checkout@v3

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"
      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: echo "$STEPS_CONTEXT"
      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}
        run: echo "$RUNNER_CONTEXT"
      - name: Dump strategy context
        env:
          STRATEGY_CONTEXT: ${{ toJson(strategy) }}
        run: echo "$STRATEGY_CONTEXT"
      - name: Dump matrix context
        env:
          MATRIX_CONTEXT: ${{ toJson(matrix) }}
        run: echo "$MATRIX_CONTEXT"

      - name: Show default environment variables
        run: |


      - name: Write to Job Summary
        if: success() || failure()
        run: echo "#WiHiiii" >> "$GITHUB_STEP_SUMMARY"

      - name: Release test ${{ vars.GITHUB_REPOSITORY_OWNER }} event ${{ github.event_name }} action  ${{ github.action }} ref ${{ github.ref }}
        run: |
          echo Repo owner x $GITHUB_REPOSITORY_OWNER x ${{ vars.GITHUB_REPOSITORY_OWNER }} x
          ls -lha
